// Data for the 8 Rakhi collection ad creatives. Prices/images pulled live
// from Shopify on 2026-08-06 — re-verify against shop/rakhi/<handle>/ before
// reusing this file for a later campaign.
export const RAKHI_COLLECTIONS = [
  {
    handle: 'the-book-worm-sister',
    eyebrow: 'Bookmarks & Desk Buddies',
    headline: 'She Reads.\nNow In Style.',
    sub: 'Bookmarks, pen pots & pencil toppers',
    fromPrice: '₹99',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/multi-purpose-box-pen-holder-toothbrush-holder-1.png?v=1783875094',
    personalized: false,
  },
  {
    handle: 'the-aesthetic-sister',
    eyebrow: 'Lamps & Decor',
    headline: 'Lights, Flowers\n& Tiny Joys.',
    sub: 'Lamps, decor & keychains',
    fromPrice: '₹99',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/ghost-balloon-lamp-1.png?v=1783875014',
    personalized: false,
  },
  {
    handle: 'the-wfh-sister',
    eyebrow: 'Desk Upgrade',
    headline: 'A Desk That\nHas Personality.',
    sub: 'Headphone stands, desk buddies & clickers',
    fromPrice: '₹129',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/ChatGPT_Image_Aug_4_2026_04_07_58_PM.png?v=1785839933',
    personalized: false,
  },
  {
    handle: 'the-kid-sibling',
    eyebrow: 'Fidgets & Games',
    headline: 'Four Things\nTo Obsess Over.',
    sub: 'Fidgets, skeletons & game boxes',
    fromPrice: '₹199',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/product_Jul_20_2026_01_27_45_PM.png?v=1784534512',
    personalized: false,
  },
  {
    handle: 'little-things-big-feels',
    eyebrow: 'Small & Thoughtful',
    headline: 'Small Budget.\nZero Compromise.',
    sub: 'Keychains, clickers & desk buddies',
    fromPrice: '₹99',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/product_Jul_30_2026_10_39_58_AM.png?v=1785388773',
    personalized: true,
  },
  {
    handle: 'the-gamer-bro',
    eyebrow: 'Desk Gear',
    headline: 'Deserves Better\nThan A Mug.',
    sub: 'Controller stands, keycaps & desk gear',
    fromPrice: '₹199',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/product_Aug_4_2026_05_33_11_PM.png?v=1785845065',
    personalized: false,
  },
  {
    handle: 'the-desk-setup-bro',
    eyebrow: 'Practical + Fun',
    headline: 'The Rare\nCombo.',
    sub: 'Pen pots, fidgets & desk dinos',
    fromPrice: '₹99',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/hoodie-pen-pot-1.png?v=1783875047',
    personalized: false,
  },
  {
    handle: 'the-car-guy-brother',
    eyebrow: 'Niche. He’ll Get It.',
    headline: 'For The 2AM\nCar Review Guy.',
    sub: 'Garage key hangers & display cases',
    fromPrice: '₹149',
    image: 'https://cdn.shopify.com/s/files/1/0784/9404/0286/files/productAug4_2026_04_14_25PM.png?v=1785840443',
    personalized: true,
  },
];
